### ISSUE TITLE
Unable to connect the wiimote

### ISSUE THREAD

**Issue by CassiopeiaStar** [cesmec/wiimote-rs#1]
I'm receiving the following error message when I attempt to connect by pressing 1 + 2 on the wiimote.
I'm running manjaro linux and I believe have all the equivalent dependencies installed.

Here are the steps:
1. run example `cargo run --example read_data`
2. press 1 + 2 on the wiimote
3. see 4 flashing lights on wiimote
4. wait...
5. Error message appears `Failed to connect to wiimote: Disconnected`
6. flashing lights stop

**Comment by cesmec** [comment]
Thanks for letting me know about this issue.
I could find the problem and it should now be fixed by commit 19d0503 and will be included in the next release (v0.1.2).
If it still doesn't work on your machine, feel free to re-open this issue.
